Create mips.xml
alexhude/FRIEND pull request #7
Opened 2017-06-15 04:46 UTC by 0x3h

this is a configuration file for the mips architecture, it does not include all instructions but the most of them.

2017-06-15 10:33 UTC, alexhude requested changes
Thanks for this config. Just a tiny bit to fix and I will merge it.

2017-06-15 10:33 UTC, alexhude commented on Configurations/mips.xml
> +	<document id="mips32" name="MIPS Architecture Reference Manual" version="A.k">
If there is a version or revision for this document, could you please add it to `version=""`?

2017-06-16 02:29 UTC, 0x3h commented on Configurations/mips.xml
> +	<document id="mips32" name="MIPS Architecture Reference Manual" version="A.k">
there is no version, i used http://www.mrc.uidaho.edu/mrc/people/jff/digital/MIPSir.html as a reference.

2017-06-16 02:38 UTC, alexhude commented on Configurations/mips.xml
> +	<document id="mips32" name="MIPS Architecture Reference Manual" version="A.k">
Hm, in this case I will probably update code to support links in the <path>

2017-06-16 02:38 UTC, merged